spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    testWhileIdle: true
    validationQuery: SELECT 1
    username: postgres
    password: ${POSTGRES_PASS}
  application:
    name: licensing-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  health:
    db:
      enabled: false
    diskspace:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    licenseService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 10s
      failureRateThreshold: 10
      eventConsumerBufferSize: 10
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
